### ISSUE TITLE
spectral compensation question

### ISSUE THREAD

**Issue by gallathan** [RobTillaart/BH1750FVI_RT#18]
really like your lib

wondering, does that compensate for the fact sensor is 'color blind' a general light intensity sensor
it seems if i set a wavelength i.e red / 660nm, the lux levels go up

I'm trying to measure the red light levels for this wavelength specifically because I'm using the lux sensor to adjust red lighting to help my chicken lay optimally

they don't care about other frequencies of light as much

would just like to have a better idea how it works

gallathan@hotmail.com

07734 107239

**Comment by RobTillaart** [comment]
The spectral compensation is experimental. It is an atempt to correct the sensitivity of the sensor at different wavelengths based upon the graph in the datasheet. 

Normally a sensor assumes full spectrum to be available. It adds up the 'energy' of the wavelengths to calculate the output. This maximum sensitivity corresponds with ~580 nm. 

I interpret the graph as the sensitivity at other wavelengths. So if the sensor is only 25% sensitive at wavelength W the real intensify of the light is 4x as high as measured. That is in short the idea of the compensation.

Does this answer your question?

**Comment by RobTillaart** [comment]
(no chicken expert disclaimer :)

What I know from chickens is that they should get at least 8 hours darkness per day to get a good rest. This dark period should start as early in the evening as possible as some roosters (do not know if you have one) will rise with daylight. If chickens get too few hours of sleep they stop laying eggs. 

I am not aware of any wavelength sensitivity for chickens, although from physics red light may also contain infrared which keeps them warmer. So the effect might be warmth instead of light. (does that makes sense?)

**Comment by RobTillaart** [comment]
Is your question answered? if so the issue can be closed.

**Comment by RobTillaart** [comment]
If this issue still exists / question remains, feel free to reopen the issue.
